apiVersion: v1
kind: Service
metadata:
  name: gtfs-rt-viewer-front
  labels:
    app: gtfs-rt-viewer-front
spec:
  selector:
    app: gtfs-rt-viewer-front
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-rt-viewer-front
  labels:
    app: gtfs-rt-viewer-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfs-rt-viewer-front
  template:
    metadata:
      labels:
        app: gtfs-rt-viewer-front
    spec:
      containers:
      - name: gtfs-rt-viewer-front
        image: docker-registry.canaltp.fr/prhod/gtfs-rt-viewer-front
        imagePullPolicy: Always
        ports:
        - containerPort: 80
